const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const sensordataSchema = new Schema(
  {
    // Meter 1
    meter_1: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_1: { type: Schema.Types.Number, required: true },
    Current_I1_meter_1: { type: Schema.Types.Number, required: true },
    Current_I2_meter_1: { type: Schema.Types.Number, required: true },
    Current_I3_meter_1: { type: Schema.Types.Number, required: true },
    Total_KW_meter_1: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_1: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_1: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_1: { type: Schema.Types.Number, required: true },
    Frequency_meter_1: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_1: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_1: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_1: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_1: { type: Schema.Types.Number, required: true },
    THD_V1_meter_1: { type: Schema.Types.Number, required: true },
    THD_V2_meter_1: { type: Schema.Types.Number, required: true },
    THD_V3_meter_1: { type: Schema.Types.Number, required: true },
    THD_I1_meter_1: { type: Schema.Types.Number, required: true },
    THD_I2_meter_1: { type: Schema.Types.Number, required: true },
    THD_I3_meter_1: { type: Schema.Types.Number, required: true },

    // Meter 2
    meter_2: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_2: { type: Schema.Types.Number, required: true },
    Current_I1_meter_2: { type: Schema.Types.Number, required: true },
    Current_I2_meter_2: { type: Schema.Types.Number, required: true },
    Current_I3_meter_2: { type: Schema.Types.Number, required: true },
    Total_KW_meter_2: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_2: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_2: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_2: { type: Schema.Types.Number, required: true },
    Frequency_meter_2: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_2: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_2: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_2: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_2: { type: Schema.Types.Number, required: true },
    THD_V1_meter_2: { type: Schema.Types.Number, required: true },
    THD_V2_meter_2: { type: Schema.Types.Number, required: true },
    THD_V3_meter_2: { type: Schema.Types.Number, required: true },
    THD_I1_meter_2: { type: Schema.Types.Number, required: true },
    THD_I2_meter_2: { type: Schema.Types.Number, required: true },
    THD_I3_meter_2: { type: Schema.Types.Number, required: true },

    // Meter 3
    meter_3: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_3: { type: Schema.Types.Number, required: true },
    Current_I1_meter_3: { type: Schema.Types.Number, required: true },
    Current_I2_meter_3: { type: Schema.Types.Number, required: true },
    Current_I3_meter_3: { type: Schema.Types.Number, required: true },
    Total_KW_meter_3: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_3: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_3: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_3: { type: Schema.Types.Number, required: true },
    Frequency_meter_3: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_3: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_3: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_3: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_3: { type: Schema.Types.Number, required: true },
    THD_V1_meter_3: { type: Schema.Types.Number, required: true },
    THD_V2_meter_3: { type: Schema.Types.Number, required: true },
    THD_V3_meter_3: { type: Schema.Types.Number, required: true },
    THD_I1_meter_3: { type: Schema.Types.Number, required: true },
    THD_I2_meter_3: { type: Schema.Types.Number, required: true },
    THD_I3_meter_3: { type: Schema.Types.Number, required: true },

    // Meter 4
    meter_4: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_4: { type: Schema.Types.Number, required: true },
    Current_I1_meter_4: { type: Schema.Types.Number, required: true },
    Current_I2_meter_4: { type: Schema.Types.Number, required: true },
    Current_I3_meter_4: { type: Schema.Types.Number, required: true },
    Total_KW_meter_4: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_4: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_4: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_4: { type: Schema.Types.Number, required: true },
    Frequency_meter_4: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_4: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_4: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_4: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_4: { type: Schema.Types.Number, required: true },
    THD_V1_meter_4: { type: Schema.Types.Number, required: true },
    THD_V2_meter_4: { type: Schema.Types.Number, required: true },
    THD_V3_meter_4: { type: Schema.Types.Number, required: true },
    THD_I1_meter_4: { type: Schema.Types.Number, required: true },
    THD_I2_meter_4: { type: Schema.Types.Number, required: true },
    THD_I3_meter_4: { type: Schema.Types.Number, required: true },

    // Meter 5
    meter_5: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_5: { type: Schema.Types.Number, required: true },
    Current_I1_meter_5: { type: Schema.Types.Number, required: true },
    Current_I2_meter_5: { type: Schema.Types.Number, required: true },
    Current_I3_meter_5: { type: Schema.Types.Number, required: true },
    Total_KW_meter_5: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_5: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_5: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_5: { type: Schema.Types.Number, required: true },
    Frequency_meter_5: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_5: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_5: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_5: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_5: { type: Schema.Types.Number, required: true },
    THD_V1_meter_5: { type: Schema.Types.Number, required: true },
    THD_V2_meter_5: { type: Schema.Types.Number, required: true },
    THD_V3_meter_5: { type: Schema.Types.Number, required: true },
    THD_I1_meter_5: { type: Schema.Types.Number, required: true },
    THD_I2_meter_5: { type: Schema.Types.Number, required: true },
    THD_I3_meter_5: { type: Schema.Types.Number, required: true },

    // Meter 6
    meter_6: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_6: { type: Schema.Types.Number, required: true },
    Current_I1_meter_6: { type: Schema.Types.Number, required: true },
    Current_I2_meter_6: { type: Schema.Types.Number, required: true },
    Current_I3_meter_6: { type: Schema.Types.Number, required: true },
    Total_KW_meter_6: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_6: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_6: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_6: { type: Schema.Types.Number, required: true },
    Frequency_meter_6: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_6: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_6: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_6: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_6: { type: Schema.Types.Number, required: true },
    THD_V1_meter_6: { type: Schema.Types.Number, required: true },
    THD_V2_meter_6: { type: Schema.Types.Number, required: true },
    THD_V3_meter_6: { type: Schema.Types.Number, required: true },
    THD_I1_meter_6: { type: Schema.Types.Number, required: true },
    THD_I2_meter_6: { type: Schema.Types.Number, required: true },
    THD_I3_meter_6: { type: Schema.Types.Number, required: true },

    // Meter 7
    meter_7: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_7: { type: Schema.Types.Number, required: true },
    Current_I1_meter_7: { type: Schema.Types.Number, required: true },
    Current_I2_meter_7: { type: Schema.Types.Number, required: true },
    Current_I3_meter_7: { type: Schema.Types.Number, required: true },
    Total_KW_meter_7: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_7: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_7: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_7: { type: Schema.Types.Number, required: true },
    Frequency_meter_7: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_7: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_7: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_7: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_7: { type: Schema.Types.Number, required: true },
    THD_V1_meter_7: { type: Schema.Types.Number, required: true },
    THD_V2_meter_7: { type: Schema.Types.Number, required: true },
    THD_V3_meter_7: { type: Schema.Types.Number, required: true },
    THD_I1_meter_7: { type: Schema.Types.Number, required: true },
    THD_I2_meter_7: { type: Schema.Types.Number, required: true },
    THD_I3_meter_7: { type: Schema.Types.Number, required: true },

    // Meter 8
    meter_8: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_8: { type: Schema.Types.Number, required: true },
    Current_I1_meter_8: { type: Schema.Types.Number, required: true },
    Current_I2_meter_8: { type: Schema.Types.Number, required: true },
    Current_I3_meter_8: { type: Schema.Types.Number, required: true },
    Total_KW_meter_8: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_8: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_8: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_8: { type: Schema.Types.Number, required: true },
    Frequency_meter_8: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_8: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_8: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_8: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_8: { type: Schema.Types.Number, required: true },
    THD_V1_meter_8: { type: Schema.Types.Number, required: true },
    THD_V2_meter_8: { type: Schema.Types.Number, required: true },
    THD_V3_meter_8: { type: Schema.Types.Number, required: true },
    THD_I1_meter_8: { type: Schema.Types.Number, required: true },
    THD_I2_meter_8: { type: Schema.Types.Number, required: true },
    THD_I3_meter_8: { type: Schema.Types.Number, required: true },

    // Meter 9
    meter_9: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_9: { type: Schema.Types.Number, required: true },
    Current_I1_meter_9: { type: Schema.Types.Number, required: true },
    Current_I2_meter_9: { type: Schema.Types.Number, required: true },
    Current_I3_meter_9: { type: Schema.Types.Number, required: true },
    Total_KW_meter_9: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_9: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_9: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_9: { type: Schema.Types.Number, required: true },
    Frequency_meter_9: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_9: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_9: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_9: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_9: { type: Schema.Types.Number, required: true },
    THD_V1_meter_9: { type: Schema.Types.Number, required: true },
    THD_V2_meter_9: { type: Schema.Types.Number, required: true },
    THD_V3_meter_9: { type: Schema.Types.Number, required: true },
    THD_I1_meter_9: { type: Schema.Types.Number, required: true },
    THD_I2_meter_9: { type: Schema.Types.Number, required: true },
    THD_I3_meter_9: { type: Schema.Types.Number, required: true },

    // Meter 10
    meter_10: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_10: { type: Schema.Types.Number, required: true },
    Current_I1_meter_10: { type: Schema.Types.Number, required: true },
    Current_I2_meter_10: { type: Schema.Types.Number, required: true },
    Current_I3_meter_10: { type: Schema.Types.Number, required: true },
    Total_KW_meter_10: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_10: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_10: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_10: { type: Schema.Types.Number, required: true },
    Frequency_meter_10: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_10: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_10: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_10: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_10: { type: Schema.Types.Number, required: true },
    THD_V1_meter_10: { type: Schema.Types.Number, required: true },
    THD_V2_meter_10: { type: Schema.Types.Number, required: true },
    THD_V3_meter_10: { type: Schema.Types.Number, required: true },
    THD_I1_meter_10: { type: Schema.Types.Number, required: true },
    THD_I2_meter_10: { type: Schema.Types.Number, required: true },
    THD_I3_meter_10: { type: Schema.Types.Number, required: true },

    // Meter 11
    meter_11: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_11: { type: Schema.Types.Number, required: true },
    Current_I1_meter_11: { type: Schema.Types.Number, required: true },
    Current_I2_meter_11: { type: Schema.Types.Number, required: true },
    Current_I3_meter_11: { type: Schema.Types.Number, required: true },
    Total_KW_meter_11: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_11: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_11: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_11: { type: Schema.Types.Number, required: true },
    Frequency_meter_11: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_11: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_11: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_11: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_11: { type: Schema.Types.Number, required: true },
    THD_V1_meter_11: { type: Schema.Types.Number, required: true },
    THD_V2_meter_11: { type: Schema.Types.Number, required: true },
    THD_V3_meter_11: { type: Schema.Types.Number, required: true },
    THD_I1_meter_11: { type: Schema.Types.Number, required: true },
    THD_I2_meter_11: { type: Schema.Types.Number, required: true },
    THD_I3_meter_11: { type: Schema.Types.Number, required: true },

    // Meter 12
    meter_12: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_12: { type: Schema.Types.Number, required: true },
    Current_I1_meter_12: { type: Schema.Types.Number, required: true },
    Current_I2_meter_12: { type: Schema.Types.Number, required: true },
    Current_I3_meter_12: { type: Schema.Types.Number, required: true },
    Total_KW_meter_12: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_12: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_12: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_12: { type: Schema.Types.Number, required: true },
    Frequency_meter_12: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_12: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_12: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_12: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_12: { type: Schema.Types.Number, required: true },
    THD_V1_meter_12: { type: Schema.Types.Number, required: true },
    THD_V2_meter_12: { type: Schema.Types.Number, required: true },
    THD_V3_meter_12: { type: Schema.Types.Number, required: true },
    THD_I1_meter_12: { type: Schema.Types.Number, required: true },
    THD_I2_meter_12: { type: Schema.Types.Number, required: true },
    THD_I3_meter_12: { type: Schema.Types.Number, required: true },

    // Meter 13
    meter_13: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_13: { type: Schema.Types.Number, required: true },
    Current_I1_meter_13: { type: Schema.Types.Number, required: true },
    Current_I2_meter_13: { type: Schema.Types.Number, required: true },
    Current_I3_meter_13: { type: Schema.Types.Number, required: true },
    Total_KW_meter_13: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_13: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_13: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_13: { type: Schema.Types.Number, required: true },
    Frequency_meter_13: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_13: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_13: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_13: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_13: { type: Schema.Types.Number, required: true },
    THD_V1_meter_13: { type: Schema.Types.Number, required: true },
    THD_V2_meter_13: { type: Schema.Types.Number, required: true },
    THD_V3_meter_13: { type: Schema.Types.Number, required: true },
    THD_I1_meter_13: { type: Schema.Types.Number, required: true },
    THD_I2_meter_13: { type: Schema.Types.Number, required: true },
    THD_I3_meter_13: { type: Schema.Types.Number, required: true },
    
    // Meter 14
    meter_14: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_14: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_14: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_14: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_14: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_14: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_14: { type: Schema.Types.Number, required: true },
    Current_I1_meter_14: { type: Schema.Types.Number, required: true },
    Current_I2_meter_14: { type: Schema.Types.Number, required: true },
    Current_I3_meter_14: { type: Schema.Types.Number, required: true },
    Total_KW_meter_14: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_14: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_14: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_14: { type: Schema.Types.Number, required: true },
    Frequency_meter_14: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_14: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_14: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_14: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_14: { type: Schema.Types.Number, required: true },
    THD_V1_meter_14: { type: Schema.Types.Number, required: true },
    THD_V2_meter_14: { type: Schema.Types.Number, required: true },
    THD_V3_meter_14: { type: Schema.Types.Number, required: true },
    THD_I1_meter_14: { type: Schema.Types.Number, required: true },
    THD_I2_meter_14: { type: Schema.Types.Number, required: true },
    THD_I3_meter_14: { type: Schema.Types.Number, required: true },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("sensordata", sensordataSchema);