const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const sensordataSchema = new Schema(
  {
    // Meter 1
    meter_1: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_1: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_1: { type: Schema.Types.Number, required: true },
    Current_I1_meter_1: { type: Schema.Types.Number, required: true },
    Current_I2_meter_1: { type: Schema.Types.Number, required: true },
    Current_I3_meter_1: { type: Schema.Types.Number, required: true },
    Total_KW_meter_1: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_1: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_1: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_1: { type: Schema.Types.Number, required: true },
    Frequency_meter_1: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_1: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_1: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_1: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_1: { type: Schema.Types.Number, required: true },

    // Meter 2
    meter_2: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_2: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_2: { type: Schema.Types.Number, required: true },
    Current_I1_meter_2: { type: Schema.Types.Number, required: true },
    Current_I2_meter_2: { type: Schema.Types.Number, required: true },
    Current_I3_meter_2: { type: Schema.Types.Number, required: true },
    Total_KW_meter_2: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_2: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_2: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_2: { type: Schema.Types.Number, required: true },
    Frequency_meter_2: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_2: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_2: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_2: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_2: { type: Schema.Types.Number, required: true },

    // Meter 3
    meter_3: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_3: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_3: { type: Schema.Types.Number, required: true },
    Current_I1_meter_3: { type: Schema.Types.Number, required: true },
    Current_I2_meter_3: { type: Schema.Types.Number, required: true },
    Current_I3_meter_3: { type: Schema.Types.Number, required: true },
    Total_KW_meter_3: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_3: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_3: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_3: { type: Schema.Types.Number, required: true },
    Frequency_meter_3: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_3: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_3: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_3: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_3: { type: Schema.Types.Number, required: true },

    // Meter 4
    meter_4: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_4: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_4: { type: Schema.Types.Number, required: true },
    Current_I1_meter_4: { type: Schema.Types.Number, required: true },
    Current_I2_meter_4: { type: Schema.Types.Number, required: true },
    Current_I3_meter_4: { type: Schema.Types.Number, required: true },
    Total_KW_meter_4: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_4: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_4: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_4: { type: Schema.Types.Number, required: true },
    Frequency_meter_4: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_4: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_4: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_4: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_4: { type: Schema.Types.Number, required: true },

    // Meter 5
    meter_5: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_5: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_5: { type: Schema.Types.Number, required: true },
    Current_I1_meter_5: { type: Schema.Types.Number, required: true },
    Current_I2_meter_5: { type: Schema.Types.Number, required: true },
    Current_I3_meter_5: { type: Schema.Types.Number, required: true },
    Total_KW_meter_5: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_5: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_5: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_5: { type: Schema.Types.Number, required: true },
    Frequency_meter_5: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_5: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_5: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_5: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_5: { type: Schema.Types.Number, required: true },


    // Meter 6
    meter_6: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_6: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_6: { type: Schema.Types.Number, required: true },
    Current_I1_meter_6: { type: Schema.Types.Number, required: true },
    Current_I2_meter_6: { type: Schema.Types.Number, required: true },
    Current_I3_meter_6: { type: Schema.Types.Number, required: true },
    Total_KW_meter_6: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_6: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_6: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_6: { type: Schema.Types.Number, required: true },
    Frequency_meter_6: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_6: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_6: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_6: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_6: { type: Schema.Types.Number, required: true },
    
    // Meter 7
    meter_7: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_7: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_7: { type: Schema.Types.Number, required: true },
    Current_I1_meter_7: { type: Schema.Types.Number, required: true },
    Current_I2_meter_7: { type: Schema.Types.Number, required: true },
    Current_I3_meter_7: { type: Schema.Types.Number, required: true },
    Total_KW_meter_7: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_7: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_7: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_7: { type: Schema.Types.Number, required: true },
    Frequency_meter_7: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_7: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_7: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_7: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_7: { type: Schema.Types.Number, required: true },
    
    // Meter 8
    meter_8: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_8: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_8: { type: Schema.Types.Number, required: true },
    Current_I1_meter_8: { type: Schema.Types.Number, required: true },
    Current_I2_meter_8: { type: Schema.Types.Number, required: true },
    Current_I3_meter_8: { type: Schema.Types.Number, required: true },
    Total_KW_meter_8: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_8: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_8: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_8: { type: Schema.Types.Number, required: true },
    Frequency_meter_8: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_8: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_8: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_8: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_8: { type: Schema.Types.Number, required: true },

    // Meter 9
    meter_9: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_9: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_9: { type: Schema.Types.Number, required: true },
    Current_I1_meter_9: { type: Schema.Types.Number, required: true },
    Current_I2_meter_9: { type: Schema.Types.Number, required: true },
    Current_I3_meter_9: { type: Schema.Types.Number, required: true },
    Total_KW_meter_9: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_9: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_9: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_9: { type: Schema.Types.Number, required: true },
    Frequency_meter_9: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_9: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_9: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_9: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_9: { type: Schema.Types.Number, required: true },
   
    // Meter 10
    meter_10: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_10: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_10: { type: Schema.Types.Number, required: true },
    Current_I1_meter_10: { type: Schema.Types.Number, required: true },
    Current_I2_meter_10: { type: Schema.Types.Number, required: true },
    Current_I3_meter_10: { type: Schema.Types.Number, required: true },
    Total_KW_meter_10: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_10: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_10: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_10: { type: Schema.Types.Number, required: true },
    Frequency_meter_10: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_10: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_10: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_10: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_10: { type: Schema.Types.Number, required: true },

    // Meter 11
    meter_11: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_11: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_11: { type: Schema.Types.Number, required: true },
    Current_I1_meter_11: { type: Schema.Types.Number, required: true },
    Current_I2_meter_11: { type: Schema.Types.Number, required: true },
    Current_I3_meter_11: { type: Schema.Types.Number, required: true },
    Total_KW_meter_11: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_11: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_11: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_11: { type: Schema.Types.Number, required: true },
    Frequency_meter_11: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_11: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_11: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_11: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_11: { type: Schema.Types.Number, required: true },

    // Meter 12
    meter_12: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_12: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_12: { type: Schema.Types.Number, required: true },
    Current_I1_meter_12: { type: Schema.Types.Number, required: true },
    Current_I2_meter_12: { type: Schema.Types.Number, required: true },
    Current_I3_meter_12: { type: Schema.Types.Number, required: true },
    Total_KW_meter_12: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_12: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_12: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_12: { type: Schema.Types.Number, required: true },
    Frequency_meter_12: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_12: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_12: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_12: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_12: { type: Schema.Types.Number, required: true },

    // Meter 13
    meter_13: { type: Schema.Types.String, required: true },
    Voltage_V1N_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V2N_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V3N_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V12_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V23_meter_13: { type: Schema.Types.Number, required: true },
    Voltage_V31_meter_13: { type: Schema.Types.Number, required: true },
    Current_I1_meter_13: { type: Schema.Types.Number, required: true },
    Current_I2_meter_13: { type: Schema.Types.Number, required: true },
    Current_I3_meter_13: { type: Schema.Types.Number, required: true },
    Total_KW_meter_13: { type: Schema.Types.Number, required: true },
    Total_KVA_meter_13: { type: Schema.Types.Number, required: true },
    Total_KVAR_meter_13: { type: Schema.Types.Number, required: true },
    Avg_PF_meter_13: { type: Schema.Types.Number, required: true },
    Frequency_meter_13: { type: Schema.Types.Number, required: true },
    TotalNet_KWH_meter_13: { type: Schema.Types.Number, required: true },
    TotalNet_KVAH_meter_13: { type: Schema.Types.Number, required: true },
    TotalNet_KVARH_meter_13: { type: Schema.Types.Number, required: true },
    Neutral_Current_meter_13: { type: Schema.Types.Number, required: true },

   // Meter 14
   meter_14: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_14: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_14: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_14: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_14: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_14: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_14: { type: Schema.Types.Number, required: true },
   Current_I1_meter_14: { type: Schema.Types.Number, required: true },
   Current_I2_meter_14: { type: Schema.Types.Number, required: true },
   Current_I3_meter_14: { type: Schema.Types.Number, required: true },
   Total_KW_meter_14: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_14: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_14: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_14: { type: Schema.Types.Number, required: true },
   Frequency_meter_14: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_14: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_14: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_14: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_14: { type: Schema.Types.Number, required: true },

   // Meter 15
   meter_15: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_15: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_15: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_15: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_15: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_15: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_15: { type: Schema.Types.Number, required: true },
   Current_I1_meter_15: { type: Schema.Types.Number, required: true },
   Current_I2_meter_15: { type: Schema.Types.Number, required: true },
   Current_I3_meter_15: { type: Schema.Types.Number, required: true },
   Total_KW_meter_15: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_15: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_15: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_15: { type: Schema.Types.Number, required: true },
   Frequency_meter_15: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_15: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_15: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_15: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_15: { type: Schema.Types.Number, required: true },

   // Meter 16
   meter_16: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_16: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_16: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_16: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_16: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_16: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_16: { type: Schema.Types.Number, required: true },
   Current_I1_meter_16: { type: Schema.Types.Number, required: true },
   Current_I2_meter_16: { type: Schema.Types.Number, required: true },
   Current_I3_meter_16: { type: Schema.Types.Number, required: true },
   Total_KW_meter_16: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_16: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_16: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_16: { type: Schema.Types.Number, required: true },
   Frequency_meter_16: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_16: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_16: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_16: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_16: { type: Schema.Types.Number, required: true },

   // Meter 17
   meter_17: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_17: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_17: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_17: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_17: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_17: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_17: { type: Schema.Types.Number, required: true },
   Current_I1_meter_17: { type: Schema.Types.Number, required: true },
   Current_I2_meter_17: { type: Schema.Types.Number, required: true },
   Current_I3_meter_17: { type: Schema.Types.Number, required: true },
   Total_KW_meter_17: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_17: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_17: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_17: { type: Schema.Types.Number, required: true },
   Frequency_meter_17: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_17: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_17: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_17: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_17: { type: Schema.Types.Number, required: true },

   // Meter 18
   meter_18: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_18: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_18: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_18: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_18: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_18: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_18: { type: Schema.Types.Number, required: true },
   Current_I1_meter_18: { type: Schema.Types.Number, required: true },
   Current_I2_meter_18: { type: Schema.Types.Number, required: true },
   Current_I3_meter_18: { type: Schema.Types.Number, required: true },
   Total_KW_meter_18: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_18: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_18: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_18: { type: Schema.Types.Number, required: true },
   Frequency_meter_18: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_18: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_18: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_18: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_18: { type: Schema.Types.Number, required: true },

   // Meter 19
   meter_19: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_19: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_19: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_19: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_19: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_19: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_19: { type: Schema.Types.Number, required: true },
   Current_I1_meter_19: { type: Schema.Types.Number, required: true },
   Current_I2_meter_19: { type: Schema.Types.Number, required: true },
   Current_I3_meter_19: { type: Schema.Types.Number, required: true },
   Total_KW_meter_19: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_19: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_19: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_19: { type: Schema.Types.Number, required: true },
   Frequency_meter_19: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_19: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_19: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_19: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_19: { type: Schema.Types.Number, required: true },

   // Meter 20
   meter_20: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_20: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_20: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_20: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_20: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_20: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_20: { type: Schema.Types.Number, required: true },
   Current_I1_meter_20: { type: Schema.Types.Number, required: true },
   Current_I2_meter_20: { type: Schema.Types.Number, required: true },
   Current_I3_meter_20: { type: Schema.Types.Number, required: true },
   Total_KW_meter_20: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_20: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_20: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_20: { type: Schema.Types.Number, required: true },
   Frequency_meter_20: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_20: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_20: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_20: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_20: { type: Schema.Types.Number, required: true },

   // Meter 21
   meter_21: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_21: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_21: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_21: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_21: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_21: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_21: { type: Schema.Types.Number, required: true },
   Current_I1_meter_21: { type: Schema.Types.Number, required: true },
   Current_I2_meter_21: { type: Schema.Types.Number, required: true },
   Current_I3_meter_21: { type: Schema.Types.Number, required: true },
   Total_KW_meter_21: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_21: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_21: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_21: { type: Schema.Types.Number, required: true },
   Frequency_meter_21: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_21: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_21: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_21: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_21: { type: Schema.Types.Number, required: true },

   // Meter 22
   meter_22: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_22: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_22: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_22: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_22: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_22: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_22: { type: Schema.Types.Number, required: true },
   Current_I1_meter_22: { type: Schema.Types.Number, required: true },
   Current_I2_meter_22: { type: Schema.Types.Number, required: true },
   Current_I3_meter_22: { type: Schema.Types.Number, required: true },
   Total_KW_meter_22: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_22: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_22: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_22: { type: Schema.Types.Number, required: true },
   Frequency_meter_22: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_22: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_22: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_22: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_22: { type: Schema.Types.Number, required: true },

   // Meter 23
   meter_23: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_23: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_23: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_23: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_23: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_23: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_23: { type: Schema.Types.Number, required: true },
   Current_I1_meter_23: { type: Schema.Types.Number, required: true },
   Current_I2_meter_23: { type: Schema.Types.Number, required: true },
   Current_I3_meter_23: { type: Schema.Types.Number, required: true },
   Total_KW_meter_23: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_23: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_23: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_23: { type: Schema.Types.Number, required: true },
   Frequency_meter_23: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_23: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_23: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_23: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_23: { type: Schema.Types.Number, required: true },

   // Meter 24
   meter_24: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_24: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_24: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_24: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_24: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_24: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_24: { type: Schema.Types.Number, required: true },
   Current_I1_meter_24: { type: Schema.Types.Number, required: true },
   Current_I2_meter_24: { type: Schema.Types.Number, required: true },
   Current_I3_meter_24: { type: Schema.Types.Number, required: true },
   Total_KW_meter_24: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_24: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_24: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_24: { type: Schema.Types.Number, required: true },
   Frequency_meter_24: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_24: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_24: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_24: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_24: { type: Schema.Types.Number, required: true },

   // Meter 25
   meter_25: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_25: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_25: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_25: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_25: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_25: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_25: { type: Schema.Types.Number, required: true },
   Current_I1_meter_25: { type: Schema.Types.Number, required: true },
   Current_I2_meter_25: { type: Schema.Types.Number, required: true },
   Current_I3_meter_25: { type: Schema.Types.Number, required: true },
   Total_KW_meter_25: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_25: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_25: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_25: { type: Schema.Types.Number, required: true },
   Frequency_meter_25: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_25: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_25: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_25: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_25: { type: Schema.Types.Number, required: true },

   // Meter 26
   meter_26: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_26: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_26: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_26: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_26: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_26: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_26: { type: Schema.Types.Number, required: true },
   Current_I1_meter_26: { type: Schema.Types.Number, required: true },
   Current_I2_meter_26: { type: Schema.Types.Number, required: true },
   Current_I3_meter_26: { type: Schema.Types.Number, required: true },
   Total_KW_meter_26: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_26: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_26: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_26: { type: Schema.Types.Number, required: true },
   Frequency_meter_26: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_26: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_26: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_26: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_26: { type: Schema.Types.Number, required: true },

   // Meter 27
   meter_27: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_27: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_27: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_27: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_27: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_27: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_27: { type: Schema.Types.Number, required: true },
   Current_I1_meter_27: { type: Schema.Types.Number, required: true },
   Current_I2_meter_27: { type: Schema.Types.Number, required: true },
   Current_I3_meter_27: { type: Schema.Types.Number, required: true },
   Total_KW_meter_27: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_27: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_27: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_27: { type: Schema.Types.Number, required: true },
   Frequency_meter_27: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_27: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_27: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_27: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_27: { type: Schema.Types.Number, required: true },

   // Meter 28
   meter_28: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_28: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_28: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_28: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_28: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_28: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_28: { type: Schema.Types.Number, required: true },
   Current_I1_meter_28: { type: Schema.Types.Number, required: true },
   Current_I2_meter_28: { type: Schema.Types.Number, required: true },
   Current_I3_meter_28: { type: Schema.Types.Number, required: true },
   Total_KW_meter_28: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_28: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_28: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_28: { type: Schema.Types.Number, required: true },
   Frequency_meter_28: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_28: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_28: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_28: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_28: { type: Schema.Types.Number, required: true },

   // Meter 29
   meter_29: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_29: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_29: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_29: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_29: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_29: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_29: { type: Schema.Types.Number, required: true },
   Current_I1_meter_29: { type: Schema.Types.Number, required: true },
   Current_I2_meter_29: { type: Schema.Types.Number, required: true },
   Current_I3_meter_29: { type: Schema.Types.Number, required: true },
   Total_KW_meter_29: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_29: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_29: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_29: { type: Schema.Types.Number, required: true },
   Frequency_meter_29: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_29: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_29: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_29: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_29: { type: Schema.Types.Number, required: true },

   // Meter 30
   meter_30: { type: Schema.Types.String, required: true },
   Voltage_V1N_meter_30: { type: Schema.Types.Number, required: true },
   Voltage_V2N_meter_30: { type: Schema.Types.Number, required: true },
   Voltage_V3N_meter_30: { type: Schema.Types.Number, required: true },
   Voltage_V12_meter_30: { type: Schema.Types.Number, required: true },
   Voltage_V23_meter_30: { type: Schema.Types.Number, required: true },
   Voltage_V31_meter_30: { type: Schema.Types.Number, required: true },
   Current_I1_meter_30: { type: Schema.Types.Number, required: true },
   Current_I2_meter_30: { type: Schema.Types.Number, required: true },
   Current_I3_meter_30: { type: Schema.Types.Number, required: true },
   Total_KW_meter_30: { type: Schema.Types.Number, required: true },
   Total_KVA_meter_30: { type: Schema.Types.Number, required: true },
   Total_KVAR_meter_30: { type: Schema.Types.Number, required: true },
   Avg_PF_meter_30: { type: Schema.Types.Number, required: true },
   Frequency_meter_30: { type: Schema.Types.Number, required: true },
   TotalNet_KWH_meter_30: { type: Schema.Types.Number, required: true },
   TotalNet_KVAH_meter_30: { type: Schema.Types.Number, required: true },
   TotalNet_KVARH_meter_30: { type: Schema.Types.Number, required: true },
   Neutral_Current_meter_30: { type: Schema.Types.Number, required: true },

   // Meter 31
meter_31: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_31: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_31: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_31: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_31: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_31: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_31: { type: Schema.Types.Number, required: true },
Current_I1_meter_31: { type: Schema.Types.Number, required: true },
Current_I2_meter_31: { type: Schema.Types.Number, required: true },
Current_I3_meter_31: { type: Schema.Types.Number, required: true },
Total_KW_meter_31: { type: Schema.Types.Number, required: true },
Total_KVA_meter_31: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_31: { type: Schema.Types.Number, required: true },
Avg_PF_meter_31: { type: Schema.Types.Number, required: true },
Frequency_meter_31: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_31: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_31: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_31: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_31: { type: Schema.Types.Number, required: true },

// Meter 32
meter_32: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_32: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_32: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_32: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_32: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_32: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_32: { type: Schema.Types.Number, required: true },
Current_I1_meter_32: { type: Schema.Types.Number, required: true },
Current_I2_meter_32: { type: Schema.Types.Number, required: true },
Current_I3_meter_32: { type: Schema.Types.Number, required: true },
Total_KW_meter_32: { type: Schema.Types.Number, required: true },
Total_KVA_meter_32: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_32: { type: Schema.Types.Number, required: true },
Avg_PF_meter_32: { type: Schema.Types.Number, required: true },
Frequency_meter_32: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_32: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_32: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_32: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_32: { type: Schema.Types.Number, required: true },

// Meter 33
meter_33: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_33: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_33: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_33: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_33: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_33: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_33: { type: Schema.Types.Number, required: true },
Current_I1_meter_33: { type: Schema.Types.Number, required: true },
Current_I2_meter_33: { type: Schema.Types.Number, required: true },
Current_I3_meter_33: { type: Schema.Types.Number, required: true },
Total_KW_meter_33: { type: Schema.Types.Number, required: true },
Total_KVA_meter_33: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_33: { type: Schema.Types.Number, required: true },
Avg_PF_meter_33: { type: Schema.Types.Number, required: true },
Frequency_meter_33: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_33: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_33: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_33: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_33: { type: Schema.Types.Number, required: true },

// Meter 34
meter_34: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_34: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_34: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_34: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_34: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_34: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_34: { type: Schema.Types.Number, required: true },
Current_I1_meter_34: { type: Schema.Types.Number, required: true },
Current_I2_meter_34: { type: Schema.Types.Number, required: true },
Current_I3_meter_34: { type: Schema.Types.Number, required: true },
Total_KW_meter_34: { type: Schema.Types.Number, required: true },
Total_KVA_meter_34: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_34: { type: Schema.Types.Number, required: true },
Avg_PF_meter_34: { type: Schema.Types.Number, required: true },
Frequency_meter_34: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_34: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_34: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_34: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_34: { type: Schema.Types.Number, required: true },

// Meter 35
meter_35: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_35: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_35: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_35: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_35: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_35: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_35: { type: Schema.Types.Number, required: true },
Current_I1_meter_35: { type: Schema.Types.Number, required: true },
Current_I2_meter_35: { type: Schema.Types.Number, required: true },
Current_I3_meter_35: { type: Schema.Types.Number, required: true },
Total_KW_meter_35: { type: Schema.Types.Number, required: true },
Total_KVA_meter_35: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_35: { type: Schema.Types.Number, required: true },
Avg_PF_meter_35: { type: Schema.Types.Number, required: true },
Frequency_meter_35: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_35: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_35: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_35: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_35: { type: Schema.Types.Number, required: true },

// Meter 36
meter_36: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_36: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_36: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_36: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_36: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_36: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_36: { type: Schema.Types.Number, required: true },
Current_I1_meter_36: { type: Schema.Types.Number, required: true },
Current_I2_meter_36: { type: Schema.Types.Number, required: true },
Current_I3_meter_36: { type: Schema.Types.Number, required: true },
Total_KW_meter_36: { type: Schema.Types.Number, required: true },
Total_KVA_meter_36: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_36: { type: Schema.Types.Number, required: true },
Avg_PF_meter_36: { type: Schema.Types.Number, required: true },
Frequency_meter_36: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_36: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_36: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_36: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_36: { type: Schema.Types.Number, required: true },

// Meter 37
meter_37: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_37: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_37: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_37: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_37: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_37: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_37: { type: Schema.Types.Number, required: true },
Current_I1_meter_37: { type: Schema.Types.Number, required: true },
Current_I2_meter_37: { type: Schema.Types.Number, required: true },
Current_I3_meter_37: { type: Schema.Types.Number, required: true },
Total_KW_meter_37: { type: Schema.Types.Number, required: true },
Total_KVA_meter_37: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_37: { type: Schema.Types.Number, required: true },
Avg_PF_meter_37: { type: Schema.Types.Number, required: true },
Frequency_meter_37: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_37: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_37: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_37: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_37: { type: Schema.Types.Number, required: true },

// Meter 38
meter_38: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_38: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_38: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_38: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_38: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_38: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_38: { type: Schema.Types.Number, required: true },
Current_I1_meter_38: { type: Schema.Types.Number, required: true },
Current_I2_meter_38: { type: Schema.Types.Number, required: true },
Current_I3_meter_38: { type: Schema.Types.Number, required: true },
Total_KW_meter_38: { type: Schema.Types.Number, required: true },
Total_KVA_meter_38: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_38: { type: Schema.Types.Number, required: true },
Avg_PF_meter_38: { type: Schema.Types.Number, required: true },
Frequency_meter_38: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_38: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_38: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_38: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_38: { type: Schema.Types.Number, required: true },

// Meter 39
meter_39: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_39: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_39: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_39: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_39: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_39: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_39: { type: Schema.Types.Number, required: true },
Current_I1_meter_39: { type: Schema.Types.Number, required: true },
Current_I2_meter_39: { type: Schema.Types.Number, required: true },
Current_I3_meter_39: { type: Schema.Types.Number, required: true },
Total_KW_meter_39: { type: Schema.Types.Number, required: true },
Total_KVA_meter_39: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_39: { type: Schema.Types.Number, required: true },
Avg_PF_meter_39: { type: Schema.Types.Number, required: true },
Frequency_meter_39: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_39: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_39: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_39: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_39: { type: Schema.Types.Number, required: true },

// Meter 40
meter_40: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_40: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_40: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_40: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_40: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_40: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_40: { type: Schema.Types.Number, required: true },
Current_I1_meter_40: { type: Schema.Types.Number, required: true },
Current_I2_meter_40: { type: Schema.Types.Number, required: true },
Current_I3_meter_40: { type: Schema.Types.Number, required: true },
Total_KW_meter_40: { type: Schema.Types.Number, required: true },
Total_KVA_meter_40: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_40: { type: Schema.Types.Number, required: true },
Avg_PF_meter_40: { type: Schema.Types.Number, required: true },
Frequency_meter_40: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_40: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_40: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_40: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_40: { type: Schema.Types.Number, required: true },

// Meter 41
meter_41: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_41: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_41: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_41: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_41: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_41: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_41: { type: Schema.Types.Number, required: true },
Current_I1_meter_41: { type: Schema.Types.Number, required: true },
Current_I2_meter_41: { type: Schema.Types.Number, required: true },
Current_I3_meter_41: { type: Schema.Types.Number, required: true },
Total_KW_meter_41: { type: Schema.Types.Number, required: true },
Total_KVA_meter_41: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_41: { type: Schema.Types.Number, required: true },
Avg_PF_meter_41: { type: Schema.Types.Number, required: true },
Frequency_meter_41: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_41: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_41: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_41: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_41: { type: Schema.Types.Number, required: true },

// Repeat for meters 42 to 67
meter_42: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_42: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_42: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_42: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_42: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_42: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_42: { type: Schema.Types.Number, required: true },
Current_I1_meter_42: { type: Schema.Types.Number, required: true },
Current_I2_meter_42: { type: Schema.Types.Number, required: true },
Current_I3_meter_42: { type: Schema.Types.Number, required: true },
Total_KW_meter_42: { type: Schema.Types.Number, required: true },
Total_KVA_meter_42: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_42: { type: Schema.Types.Number, required: true },
Avg_PF_meter_42: { type: Schema.Types.Number, required: true },
Frequency_meter_42: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_42: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_42: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_42: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_42: { type: Schema.Types.Number, required: true },

// Meter 43
meter_43: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_43: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_43: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_43: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_43: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_43: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_43: { type: Schema.Types.Number, required: true },
Current_I1_meter_43: { type: Schema.Types.Number, required: true },
Current_I2_meter_43: { type: Schema.Types.Number, required: true },
Current_I3_meter_43: { type: Schema.Types.Number, required: true },
Total_KW_meter_43: { type: Schema.Types.Number, required: true },
Total_KVA_meter_43: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_43: { type: Schema.Types.Number, required: true },
Avg_PF_meter_43: { type: Schema.Types.Number, required: true },
Frequency_meter_43: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_43: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_43: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_43: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_43: { type: Schema.Types.Number, required: true },

// Meter 44
meter_44: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_44: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_44: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_44: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_44: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_44: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_44: { type: Schema.Types.Number, required: true },
Current_I1_meter_44: { type: Schema.Types.Number, required: true },
Current_I2_meter_44: { type: Schema.Types.Number, required: true },
Current_I3_meter_44: { type: Schema.Types.Number, required: true },
Total_KW_meter_44: { type: Schema.Types.Number, required: true },
Total_KVA_meter_44: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_44: { type: Schema.Types.Number, required: true },
Avg_PF_meter_44: { type: Schema.Types.Number, required: true },
Frequency_meter_44: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_44: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_44: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_44: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_44: { type: Schema.Types.Number, required: true },

// Meter 45
meter_45: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_45: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_45: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_45: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_45: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_45: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_45: { type: Schema.Types.Number, required: true },
Current_I1_meter_45: { type: Schema.Types.Number, required: true },
Current_I2_meter_45: { type: Schema.Types.Number, required: true },
Current_I3_meter_45: { type: Schema.Types.Number, required: true },
Total_KW_meter_45: { type: Schema.Types.Number, required: true },
Total_KVA_meter_45: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_45: { type: Schema.Types.Number, required: true },
Avg_PF_meter_45: { type: Schema.Types.Number, required: true },
Frequency_meter_45: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_45: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_45: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_45: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_45: { type: Schema.Types.Number, required: true },

// Meter 46
meter_46: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_46: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_46: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_46: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_46: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_46: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_46: { type: Schema.Types.Number, required: true },
Current_I1_meter_46: { type: Schema.Types.Number, required: true },
Current_I2_meter_46: { type: Schema.Types.Number, required: true },
Current_I3_meter_46: { type: Schema.Types.Number, required: true },
Total_KW_meter_46: { type: Schema.Types.Number, required: true },
Total_KVA_meter_46: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_46: { type: Schema.Types.Number, required: true },
Avg_PF_meter_46: { type: Schema.Types.Number, required: true },
Frequency_meter_46: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_46: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_46: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_46: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_46: { type: Schema.Types.Number, required: true },

// Meter 47
meter_47: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_47: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_47: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_47: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_47: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_47: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_47: { type: Schema.Types.Number, required: true },
Current_I1_meter_47: { type: Schema.Types.Number, required: true },
Current_I2_meter_47: { type: Schema.Types.Number, required: true },
Current_I3_meter_47: { type: Schema.Types.Number, required: true },
Total_KW_meter_47: { type: Schema.Types.Number, required: true },
Total_KVA_meter_47: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_47: { type: Schema.Types.Number, required: true },
Avg_PF_meter_47: { type: Schema.Types.Number, required: true },
Frequency_meter_47: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_47: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_47: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_47: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_47: { type: Schema.Types.Number, required: true },

// Meter 48
meter_48: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_48: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_48: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_48: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_48: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_48: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_48: { type: Schema.Types.Number, required: true },
Current_I1_meter_48: { type: Schema.Types.Number, required: true },
Current_I2_meter_48: { type: Schema.Types.Number, required: true },
Current_I3_meter_48: { type: Schema.Types.Number, required: true },
Total_KW_meter_48: { type: Schema.Types.Number, required: true },
Total_KVA_meter_48: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_48: { type: Schema.Types.Number, required: true },
Avg_PF_meter_48: { type: Schema.Types.Number, required: true },
Frequency_meter_48: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_48: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_48: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_48: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_48: { type: Schema.Types.Number, required: true },

// Meter 49
meter_49: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_49: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_49: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_49: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_49: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_49: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_49: { type: Schema.Types.Number, required: true },
Current_I1_meter_49: { type: Schema.Types.Number, required: true },
Current_I2_meter_49: { type: Schema.Types.Number, required: true },
Current_I3_meter_49: { type: Schema.Types.Number, required: true },
Total_KW_meter_49: { type: Schema.Types.Number, required: true },
Total_KVA_meter_49: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_49: { type: Schema.Types.Number, required: true },
Avg_PF_meter_49: { type: Schema.Types.Number, required: true },
Frequency_meter_49: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_49: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_49: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_49: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_49: { type: Schema.Types.Number, required: true },

// Meter 50
meter_50: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_50: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_50: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_50: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_50: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_50: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_50: { type: Schema.Types.Number, required: true },
Current_I1_meter_50: { type: Schema.Types.Number, required: true },
Current_I2_meter_50: { type: Schema.Types.Number, required: true },
Current_I3_meter_50: { type: Schema.Types.Number, required: true },
Total_KW_meter_50: { type: Schema.Types.Number, required: true },
Total_KVA_meter_50: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_50: { type: Schema.Types.Number, required: true },
Avg_PF_meter_50: { type: Schema.Types.Number, required: true },
Frequency_meter_50: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_50: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_50: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_50: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_50: { type: Schema.Types.Number, required: true },

// Meter 51
meter_51: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_51: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_51: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_51: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_51: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_51: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_51: { type: Schema.Types.Number, required: true },
Current_I1_meter_51: { type: Schema.Types.Number, required: true },
Current_I2_meter_51: { type: Schema.Types.Number, required: true },
Current_I3_meter_51: { type: Schema.Types.Number, required: true },
Total_KW_meter_51: { type: Schema.Types.Number, required: true },
Total_KVA_meter_51: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_51: { type: Schema.Types.Number, required: true },
Avg_PF_meter_51: { type: Schema.Types.Number, required: true },
Frequency_meter_51: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_51: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_51: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_51: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_51: { type: Schema.Types.Number, required: true },

// Meter 52
meter_52: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_52: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_52: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_52: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_52: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_52: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_52: { type: Schema.Types.Number, required: true },
Current_I1_meter_52: { type: Schema.Types.Number, required: true },
Current_I2_meter_52: { type: Schema.Types.Number, required: true },
Current_I3_meter_52: { type: Schema.Types.Number, required: true },
Total_KW_meter_52: { type: Schema.Types.Number, required: true },
Total_KVA_meter_52: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_52: { type: Schema.Types.Number, required: true },
Avg_PF_meter_52: { type: Schema.Types.Number, required: true },
Frequency_meter_52: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_52: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_52: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_52: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_52: { type: Schema.Types.Number, required: true },

// Meter 53
meter_53: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_53: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_53: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_53: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_53: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_53: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_53: { type: Schema.Types.Number, required: true },
Current_I1_meter_53: { type: Schema.Types.Number, required: true },
Current_I2_meter_53: { type: Schema.Types.Number, required: true },
Current_I3_meter_53: { type: Schema.Types.Number, required: true },
Total_KW_meter_53: { type: Schema.Types.Number, required: true },
Total_KVA_meter_53: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_53: { type: Schema.Types.Number, required: true },
Avg_PF_meter_53: { type: Schema.Types.Number, required: true },
Frequency_meter_53: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_53: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_53: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_53: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_53: { type: Schema.Types.Number, required: true },

// Meter 54
meter_54: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_54: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_54: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_54: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_54: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_54: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_54: { type: Schema.Types.Number, required: true },
Current_I1_meter_54: { type: Schema.Types.Number, required: true },
Current_I2_meter_54: { type: Schema.Types.Number, required: true },
Current_I3_meter_54: { type: Schema.Types.Number, required: true },
Total_KW_meter_54: { type: Schema.Types.Number, required: true },
Total_KVA_meter_54: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_54: { type: Schema.Types.Number, required: true },
Avg_PF_meter_54: { type: Schema.Types.Number, required: true },
Frequency_meter_54: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_54: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_54: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_54: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_54: { type: Schema.Types.Number, required: true },

// Meter 55
meter_55: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_55: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_55: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_55: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_55: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_55: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_55: { type: Schema.Types.Number, required: true },
Current_I1_meter_55: { type: Schema.Types.Number, required: true },
Current_I2_meter_55: { type: Schema.Types.Number, required: true },
Current_I3_meter_55: { type: Schema.Types.Number, required: true },
Total_KW_meter_55: { type: Schema.Types.Number, required: true },
Total_KVA_meter_55: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_55: { type: Schema.Types.Number, required: true },
Avg_PF_meter_55: { type: Schema.Types.Number, required: true },
Frequency_meter_55: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_55: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_55: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_55: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_55: { type: Schema.Types.Number, required: true },

// Meter 56
meter_56: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_56: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_56: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_56: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_56: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_56: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_56: { type: Schema.Types.Number, required: true },
Current_I1_meter_56: { type: Schema.Types.Number, required: true },
Current_I2_meter_56: { type: Schema.Types.Number, required: true },
Current_I3_meter_56: { type: Schema.Types.Number, required: true },
Total_KW_meter_56: { type: Schema.Types.Number, required: true },
Total_KVA_meter_56: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_56: { type: Schema.Types.Number, required: true },
Avg_PF_meter_56: { type: Schema.Types.Number, required: true },
Frequency_meter_56: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_56: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_56: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_56: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_56: { type: Schema.Types.Number, required: true },

// Meter 57
meter_57: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_57: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_57: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_57: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_57: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_57: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_57: { type: Schema.Types.Number, required: true },
Current_I1_meter_57: { type: Schema.Types.Number, required: true },
Current_I2_meter_57: { type: Schema.Types.Number, required: true },
Current_I3_meter_57: { type: Schema.Types.Number, required: true },
Total_KW_meter_57: { type: Schema.Types.Number, required: true },
Total_KVA_meter_57: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_57: { type: Schema.Types.Number, required: true },
Avg_PF_meter_57: { type: Schema.Types.Number, required: true },
Frequency_meter_57: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_57: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_57: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_57: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_57: { type: Schema.Types.Number, required: true },

// Meter 58
meter_58: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_58: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_58: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_58: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_58: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_58: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_58: { type: Schema.Types.Number, required: true },
Current_I1_meter_58: { type: Schema.Types.Number, required: true },
Current_I2_meter_58: { type: Schema.Types.Number, required: true },
Current_I3_meter_58: { type: Schema.Types.Number, required: true },
Total_KW_meter_58: { type: Schema.Types.Number, required: true },
Total_KVA_meter_58: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_58: { type: Schema.Types.Number, required: true },
Avg_PF_meter_58: { type: Schema.Types.Number, required: true },
Frequency_meter_58: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_58: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_58: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_58: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_58: { type: Schema.Types.Number, required: true },

// Meter 59
meter_59: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_59: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_59: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_59: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_59: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_59: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_59: { type: Schema.Types.Number, required: true },
Current_I1_meter_59: { type: Schema.Types.Number, required: true },
Current_I2_meter_59: { type: Schema.Types.Number, required: true },
Current_I3_meter_59: { type: Schema.Types.Number, required: true },
Total_KW_meter_59: { type: Schema.Types.Number, required: true },
Total_KVA_meter_59: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_59: { type: Schema.Types.Number, required: true },
Avg_PF_meter_59: { type: Schema.Types.Number, required: true },
Frequency_meter_59: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_59: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_59: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_59: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_59: { type: Schema.Types.Number, required: true },

// Meter 60
meter_60: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_60: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_60: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_60: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_60: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_60: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_60: { type: Schema.Types.Number, required: true },
Current_I1_meter_60: { type: Schema.Types.Number, required: true },
Current_I2_meter_60: { type: Schema.Types.Number, required: true },
Current_I3_meter_60: { type: Schema.Types.Number, required: true },
Total_KW_meter_60: { type: Schema.Types.Number, required: true },
Total_KVA_meter_60: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_60: { type: Schema.Types.Number, required: true },
Avg_PF_meter_60: { type: Schema.Types.Number, required: true },
Frequency_meter_60: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_60: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_60: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_60: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_60: { type: Schema.Types.Number, required: true },

// Meter 61
meter_61: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_61: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_61: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_61: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_61: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_61: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_61: { type: Schema.Types.Number, required: true },
Current_I1_meter_61: { type: Schema.Types.Number, required: true },
Current_I2_meter_61: { type: Schema.Types.Number, required: true },
Current_I3_meter_61: { type: Schema.Types.Number, required: true },
Total_KW_meter_61: { type: Schema.Types.Number, required: true },
Total_KVA_meter_61: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_61: { type: Schema.Types.Number, required: true },
Avg_PF_meter_61: { type: Schema.Types.Number, required: true },
Frequency_meter_61: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_61: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_61: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_61: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_61: { type: Schema.Types.Number, required: true },

// Meter 62
meter_62: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_62: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_62: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_62: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_62: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_62: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_62: { type: Schema.Types.Number, required: true },
Current_I1_meter_62: { type: Schema.Types.Number, required: true },
Current_I2_meter_62: { type: Schema.Types.Number, required: true },
Current_I3_meter_62: { type: Schema.Types.Number, required: true },
Total_KW_meter_62: { type: Schema.Types.Number, required: true },
Total_KVA_meter_62: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_62: { type: Schema.Types.Number, required: true },
Avg_PF_meter_62: { type: Schema.Types.Number, required: true },
Frequency_meter_62: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_62: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_62: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_62: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_62: { type: Schema.Types.Number, required: true },

// Meter 63
meter_63: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_63: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_63: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_63: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_63: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_63: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_63: { type: Schema.Types.Number, required: true },
Current_I1_meter_63: { type: Schema.Types.Number, required: true },
Current_I2_meter_63: { type: Schema.Types.Number, required: true },
Current_I3_meter_63: { type: Schema.Types.Number, required: true },
Total_KW_meter_63: { type: Schema.Types.Number, required: true },
Total_KVA_meter_63: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_63: { type: Schema.Types.Number, required: true },
Avg_PF_meter_63: { type: Schema.Types.Number, required: true },
Frequency_meter_63: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_63: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_63: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_63: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_63: { type: Schema.Types.Number, required: true },

// Meter 64
meter_64: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_64: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_64: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_64: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_64: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_64: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_64: { type: Schema.Types.Number, required: true },
Current_I1_meter_64: { type: Schema.Types.Number, required: true },
Current_I2_meter_64: { type: Schema.Types.Number, required: true },
Current_I3_meter_64: { type: Schema.Types.Number, required: true },
Total_KW_meter_64: { type: Schema.Types.Number, required: true },
Total_KVA_meter_64: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_64: { type: Schema.Types.Number, required: true },
Avg_PF_meter_64: { type: Schema.Types.Number, required: true },
Frequency_meter_64: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_64: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_64: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_64: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_64: { type: Schema.Types.Number, required: true },

// Meter 65
meter_65: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_65: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_65: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_65: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_65: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_65: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_65: { type: Schema.Types.Number, required: true },
Current_I1_meter_65: { type: Schema.Types.Number, required: true },
Current_I2_meter_65: { type: Schema.Types.Number, required: true },
Current_I3_meter_65: { type: Schema.Types.Number, required: true },
Total_KW_meter_65: { type: Schema.Types.Number, required: true },
Total_KVA_meter_65: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_65: { type: Schema.Types.Number, required: true },
Avg_PF_meter_65: { type: Schema.Types.Number, required: true },
Frequency_meter_65: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_65: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_65: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_65: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_65: { type: Schema.Types.Number, required: true },

// Meter 66
meter_66: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_66: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_66: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_66: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_66: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_66: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_66: { type: Schema.Types.Number, required: true },
Current_I1_meter_66: { type: Schema.Types.Number, required: true },
Current_I2_meter_66: { type: Schema.Types.Number, required: true },
Current_I3_meter_66: { type: Schema.Types.Number, required: true },
Total_KW_meter_66: { type: Schema.Types.Number, required: true },
Total_KVA_meter_66: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_66: { type: Schema.Types.Number, required: true },
Avg_PF_meter_66: { type: Schema.Types.Number, required: true },
Frequency_meter_66: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_66: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_66: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_66: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_66: { type: Schema.Types.Number, required: true },

// Meter 67
meter_67: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_67: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_67: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_67: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_67: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_67: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_67: { type: Schema.Types.Number, required: true },
Current_I1_meter_67: { type: Schema.Types.Number, required: true },
Current_I2_meter_67: { type: Schema.Types.Number, required: true },
Current_I3_meter_67: { type: Schema.Types.Number, required: true },
Total_KW_meter_67: { type: Schema.Types.Number, required: true },
Total_KVA_meter_67: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_67: { type: Schema.Types.Number, required: true },
Avg_PF_meter_67: { type: Schema.Types.Number, required: true },
Frequency_meter_67: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_67: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_67: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_67: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_67: { type: Schema.Types.Number, required: true },

// Meter 68
meter_68: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_68: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_68: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_68: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_68: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_68: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_68: { type: Schema.Types.Number, required: true },
Current_I1_meter_68: { type: Schema.Types.Number, required: true },
Current_I2_meter_68: { type: Schema.Types.Number, required: true },
Current_I3_meter_68: { type: Schema.Types.Number, required: true },
Total_KW_meter_68: { type: Schema.Types.Number, required: true },
Total_KVA_meter_68: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_68: { type: Schema.Types.Number, required: true },
Avg_PF_meter_68: { type: Schema.Types.Number, required: true },
Frequency_meter_68: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_68: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_68: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_68: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_68: { type: Schema.Types.Number, required: true },

// Meter 69
meter_69: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_69: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_69: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_69: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_69: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_69: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_69: { type: Schema.Types.Number, required: true },
Current_I1_meter_69: { type: Schema.Types.Number, required: true },
Current_I2_meter_69: { type: Schema.Types.Number, required: true },
Current_I3_meter_69: { type: Schema.Types.Number, required: true },
Total_KW_meter_69: { type: Schema.Types.Number, required: true },
Total_KVA_meter_69: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_69: { type: Schema.Types.Number, required: true },
Avg_PF_meter_69: { type: Schema.Types.Number, required: true },
Frequency_meter_69: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_69: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_69: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_69: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_69: { type: Schema.Types.Number, required: true },

// Meter 70
meter_70: { type: Schema.Types.String, required: true },
Voltage_V1N_meter_70: { type: Schema.Types.Number, required: true },
Voltage_V2N_meter_70: { type: Schema.Types.Number, required: true },
Voltage_V3N_meter_70: { type: Schema.Types.Number, required: true },
Voltage_V12_meter_70: { type: Schema.Types.Number, required: true },
Voltage_V23_meter_70: { type: Schema.Types.Number, required: true },
Voltage_V31_meter_70: { type: Schema.Types.Number, required: true },
Current_I1_meter_70: { type: Schema.Types.Number, required: true },
Current_I2_meter_70: { type: Schema.Types.Number, required: true },
Current_I3_meter_70: { type: Schema.Types.Number, required: true },
Total_KW_meter_70: { type: Schema.Types.Number, required: true },
Total_KVA_meter_70: { type: Schema.Types.Number, required: true },
Total_KVAR_meter_70: { type: Schema.Types.Number, required: true },
Avg_PF_meter_70: { type: Schema.Types.Number, required: true },
Frequency_meter_70: { type: Schema.Types.Number, required: true },
TotalNet_KWH_meter_70: { type: Schema.Types.Number, required: true },
TotalNet_KVAH_meter_70: { type: Schema.Types.Number, required: true },
TotalNet_KVARH_meter_70: { type: Schema.Types.Number, required: true },
Neutral_Current_meter_70: { type: Schema.Types.Number, required: true },

    timestamp: {
      type: Date,
      default: function () {
        const now = new Date();
        const IST_OFFSET = 5.5 * 60 * 60 * 1000; // IST offset in milliseconds
        return new Date(now.getTime() + IST_OFFSET);
      },
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("sensordata", sensordataSchema);
